spring.datasource.url=jdbc:sqlite:telemetria-60min.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
# não sobe servidor HTTP — app roda só em background
spring.main.web-application-type=none

# nome da aplicação nos logs
spring.application.name=iot-data-consumer

